---
apiVersion: v1
kind: Service
metadata:
  name: dev-api
spec:
  type: LoadBalancer
  selector:
    app: dev-api
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-api
  labels:
    app: dev-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-api
  template:
    metadata:
      labels:
        app: dev-api
    spec:
      containers:
        - name: dev-api
          image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/my-repository/dev-api:latest
          ports:
            - containerPort: 8080